package config

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/hashicorp/hcl/v2/hclsimple"
	"github.com/lox/skillyard/internal/agent"
)

type File struct {
	Agents []AgentBlock `hcl:"agent,block"`
}

func DefaultContent() ([]byte, agent.Registry, error) {
	registry, err := agent.BuiltInRegistry()
	if err != nil {
		return nil, agent.Registry{}, err
	}
	var buf bytes.Buffer
	buf.WriteString("# skillyard global agent skills configuration\n")
	buf.WriteString("# Generated by `skillyard setup`.\n\n")
	for _, a := range registry.EnabledAgents() {
		fmt.Fprintf(&buf, "agent %q {\n", a.Name)
		fmt.Fprintf(&buf, "  enabled    = %t\n", a.Enabled)
		fmt.Fprintf(&buf, "  skills_dir = %q\n", setupSkillsDirExpr(a))
		buf.WriteString("}\n\n")
	}
	return buf.Bytes(), registry, nil
}

func setupSkillsDirExpr(a agent.Agent) string {
	if a.Name == agent.Codex {
		if os.Getenv("CODEX_HOME") != "" {
			return filepath.Join("$CODEX_HOME", "skills")
		}
		return "~/.codex/skills"
	}
	if a.Name == agent.Amp {
		return "~/.config/agents/skills"
	}
	if a.SkillsDirExpr != "" {
		return a.SkillsDirExpr
	}
	return a.SkillsDir
}

type AgentBlock struct {
	Name      string `hcl:"name,label"`
	Enabled   *bool  `hcl:"enabled,optional"`
	SkillsDir string `hcl:"skills_dir,optional"`
}

func LoadAgents(path string) (agent.Registry, error) {
	registry, err := agent.BuiltInRegistry()
	if err != nil {
		return agent.Registry{}, err
	}
	var file File
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return registry, nil
	} else if err != nil {
		return agent.Registry{}, fmt.Errorf("inspect config %s: %w", path, err)
	}
	if err := hclsimple.DecodeFile(path, nil, &file); err != nil {
		return agent.Registry{}, fmt.Errorf("parse config %s: %w", path, err)
	}
	for _, block := range file.Agents {
		existing, ok := registry.Agents[block.Name]
		if !ok {
			existing = agent.Agent{
				Name:    block.Name,
				Enabled: true,
			}
		}
		if block.Enabled != nil {
			existing.Enabled = *block.Enabled
		}
		if block.SkillsDir != "" {
			existing.SkillsDir = block.SkillsDir
			existing.SkillsDirExpr = block.SkillsDir
		}
		if err := registry.Upsert(existing); err != nil {
			return agent.Registry{}, err
		}
	}
	return registry, nil
}
